### ISSUE TITLE
[Request] Add a todo count in tray and support for more multi-line comments

### ISSUE THREAD

**Issue by charlesmilette** [kantlove/vscode-todo-parser#1]
That addon is a great tool.

I'd like to request some things.

First I'd like to have a count in the tray for the current file or the work files (can be changed), a bit like that:
![capture](https://cloud.githubusercontent.com/assets/6440374/15729968/b8362226-2836-11e6-8406-1ff8d110b685.PNG)

Secondly, I'd like to have support for TODOs like that:

```c#
// TODO: This is a todo with
// many lines
// and it is currently not supported
```
It currently gives
```
1.
File Untitled-1. Line 0, column 0
----------------------------------
TODO: This is a todo with
```
but should give
```
1.
File Untitled-1. Line 0, column 0
----------------------------------
TODO: This is a todo with many lines and it is currently not supported
```

**Comment by kantlove** [comment]
Hi @charlesmilette ,
Thanks for your suggestion.
Those features are actually in development. However those will not arrive soon because I'm doing my thesis :worried:

**Comment by kantlove** [comment]
Status bar counter is complete

**Comment by charlesmilette** [comment]
Thanks ! Will try that tomorrow.

**Comment by charlesmilette** [comment]
Just tried it, it's great.

Can you make so that when you click on the icon in the status bar, it does the same as when using the command palette and selecting "Parse TODOs"?

**Comment by kantlove** [comment]
Cool idea :+1: . It's done [v1.1](https://github.com/kantlove/vscode-todo-parser/tree/1.1.0)
