### ISSUE TITLE
Can't get it work with vscode 1.4

### ISSUE THREAD

**Issue by tommiv** [kantlove/vscode-todo-parser#13]
Hi guys. I see an empty output panel when I run the "todo (all files)" command, while todos are clearly there:

![](https://i.imgur.com/Eac3n4X.png)

At first I thought that the `node_modules` folder is too big, so I excluded it in the settings

```javascript
"TodoParser": {
    "exclude": ["node_modules"]
 }
```

but it makes no difference. I tried different formats 

```
// todo: x
// Todo: x
// TODO: x
//todo: x
```

with no luck.

I see that parser is doing something, because I see spawning helpers when I run the command:

![](https://i.imgur.com/qUBbXeO.png)

Also the command for the current file **sometimes** throws an exception. It looks like a random error.

![](https://i.imgur.com/n5hlxnn.png)

P.S. I never tried it with code < 1.4 so I cannot confirm if it's new behavior.

**Comment by jdehaan** [comment]
Same behavior for me with vscode 1.4 and python comments. So the bug seems not to be affecting one language only.

**Comment by kantlove** [comment]
Thank you for such a detailed issue :+1: 
I have updated the extension to [v1.5.1](https://github.com/kantlove/vscode-todo-parser/releases/tag/v1.5.1) which includes code re-structure and fixes.

Tested on my machine with vscode 1.4 and there is no issue. Can you re-check with the latest version?

 Also, the way you use the `exclude` entry in settings is incorrect. The allowed value is file extension (e.g. cpp, java) only. I have added a new entry `folderExclude` that allow **folder names** you want to exclude.

**Comment by tommiv** [comment]
I'm sorry, but now I get 
> command 'extension.parseAllFiles' not found
and 
> command 'extension.parseCurrentFile' not found
for "all files" and "current file" menu items respectively. This time I get it every time I run the command, it's not random anymore.

**Comment by kantlove** [comment]
Oh. I think the problem is that the extension did not start property when users use the commands. I changed it to start on startup.

Could you re-install and check again?

**Comment by tommiv** [comment]
There are no errors now, but the output panel is not showing. I still see code helpers are spawning, so definetely something is going on.

**Comment by kantlove** [comment]
May I ask which OS you are running?
On my Win10 pc, the panel shows.
![capture](https://cloud.githubusercontent.com/assets/8610576/17475115/9b8db1de-5d83-11e6-85d3-3fb3c0777b2b.JPG)

Maybe try re-installing one more time?

Thank you for spending time helping me debug. Much appreciate :two_men_holding_hands:

**Comment by tommiv** [comment]
It's os x 10.11.6

**Comment by kantlove** [comment]
Maybe it takes too long to parse the TODOs. Could you try excluding large folders with `folderExclude` setting.

**Comment by tommiv** [comment]
Already did – `"folderExclude": ["node_modules"]`. Also I suppose that "current document" command should run pretty quick since it's read only one file.

**Comment by kantlove** [comment]
Does the TODO counter at the status bar (bottom bar) work? and how large is your file?

**Comment by tommiv** [comment]
No counter. File is pretty small – 45 lines of code.

**Comment by kantlove** [comment]
I guess that means this icon does not show 
![capture](https://cloud.githubusercontent.com/assets/8610576/17476217/10ff6dae-5d89-11e6-9dcb-0f68dde3b4c7.JPG)
Do you spot error in the developer console of vscode? (open by *Help->Toggle Developer Tools*)

**Comment by tommiv** [comment]
Actually, yes:

```
workbench.main.js:117 Cannot read property 'find' of undefined: TypeError: Cannot read property 'find' of undefined
    at Function.FileFilter.check (/Users/tommi/.vscode/extensions/minhthai.vscode-todo-parser-1.5.1/out/src/classes/FileFilter.js:18:74)
    at Function.FileFilter.filter (/Users/tommi/.vscode/extensions/minhthai.vscode-todo-parser-1.5.1/out/src/classes/FileFilter.js:10:22)
    at /Users/tommi/.vscode/extensions/minhthai.vscode-todo-parser-1.5.1/out/src/types/CommandType.js:60:42
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Now when I saw the trace, my assumption is it requires `exclude` field of settings to exist (I don't have one, only folderExclude). Looks like I was right, I added empty array `exclude: []`, and now I see an icon and the output panel, but it still empty:

![](https://i.imgur.com/tP4DoM1.png)

Now the error is changed to 

```
shell.ts:422Cannot read property 'length' of undefined: TypeError: Cannot read property 'length' of undefined
    at Function.Parser.startsWith (/Users/tommi/.vscode/extensions/minhthai.vscode-todo-parser-1.5.1/out/src/classes/Parser.js:90:61)
    at Function.Parser.refine (/Users/tommi/.vscode/extensions/minhthai.vscode-todo-parser-1.5.1/out/src/classes/Parser.js:69:30)
    at Function.Parser.matchText (/Users/tommi/.vscode/extensions/minhthai.vscode-todo-parser-1.5.1/out/src/classes/Parser.js:46:33)
    at Function.Parser.parseSingleFile (/Users/tommi/.vscode/extensions/minhthai.vscode-todo-parser-1.5.1/out/src/classes/Parser.js:26:47)
    at Function.Parser.parse (/Users/tommi/.vscode/extensions/minhthai.vscode-todo-parser-1.5.1/out/src/classes/Parser.js:11:39)
    at /Users/tommi/.vscode/extensions/minhthai.vscode-todo-parser-1.5.1/out/src/types/CommandType.js:11:42
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by tommiv** [comment]
Finally made it

![](https://i.imgur.com/y2vNWRF.png)

`"markers": []` was also required. I believe the plugin need some default config or config check :)

**Comment by kantlove** [comment]
Thank you so much pal :+1: 

Well, I had that in mind but I guess there is always a hole :confused:
Can you update to v1.5.2 and try the extension again ?

**Comment by tommiv** [comment]
Looks like 1.5.2 works well. Thank you!
