### ISSUE TITLE
Feature Request: parse TypeScript files

### ISSUE THREAD

**Issue by McSnooze** [kantlove/vscode-todo-parser#14]
I would like to be able to use your extension with TypeScript projects.

**Comment by kantlove** [comment]
It is added in [v1.6.0](https://github.com/kantlove/vscode-todo-parser/releases/tag/v1.6.0). :+1: 
Please update the extension.

**Comment by McSnooze** [comment]
Did you forgot the '.ts' file extensions in the supported languages array (in regex_store.ts)?

**Comment by kantlove** [comment]
No, it is not needed anymore.
