### ISSUE TITLE
Support for "# TODO:" style Todo

### ISSUE THREAD

**Issue by Zenohate** [kantlove/vscode-todo-parser#15]
This would be awesome if you could add such a functionality.

Lots of languages use this kind of comments such as Python, Elixir, Bash...

**Comment by kantlove** [comment]
Python is already supported. I think it works fine.
I have added support for Elixir and Bash.

Please update the extension to v1.7.0 and enjoy :blush:

**Comment by acgmohu** [comment]
it seems could not work.

I think my configure is ok.

```json
{
        "TodoParser": {
        "exclude": [
            "py"],
        "markers": [
            "TODO:",
            "TODO",
            "REMINDER:"]
    }
}
```
I open one .py file, ctrl+p, > Parse Todos(current document), show "No TODOs found".

**Comment by kantlove** [comment]
Because you **excluded** all **py** files in your configuration. It is the line:
```
"exclude": ["py"]
```

**Comment by acgmohu** [comment]
I have changed to 
```
    "TodoParser": {
        "exclude": ["py"],
        "markers": [
            "TODO:",
            "TODO",
            "FIXME:"]
    }
}
```.

but it still could not work.

**Comment by acgmohu** [comment]
Sorry, I got it. -_- my faults.  Thank you. @kantlove

**Comment by kantlove** [comment]
No problem. Enjoy coding :smile_cat:
