### ISSUE TITLE
vscode hangs when i open user settings file from command palette

### ISSUE THREAD

**Issue by canfoderiskii** [kantlove/vscode-todo-parser#18]
vscode-todo-parser version: 1.7.2

most of the issue description have been written here: [vscode issue #10664](https://github.com/Microsoft/vscode/issues/10664)

PS: as long as i open user settings file from command palette, one of Code.exe process consume a higher percentage of CPU time, then i can reproduce the issue of editor hanging by typing some words.

**Comment by kantlove** [comment]
I cannot reproduce this on my machine. Could you provide a screenshot of what you did to the setting file that causes the problem? (or your setting file if possible)

**Comment by canfoderiskii** [comment]
@kantlove just random words, for example: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

In addition, autocomplete for config in JSON file does not work at that time.

**Comment by kantlove** [comment]
Did you run any command of the extension before that? It is reported that the command **Parse TODOs (all files)** may hang vscode if run on a large project.

**Comment by canfoderiskii** [comment]
@kantlove , nope, i didnt run any command of your extension. i only used "preference: open user settings" command from palette.

**Comment by kantlove** [comment]
Could you update to v1.8.0 and check again?

**Comment by canfoderiskii** [comment]
@kantlove updated to v1.8.0, the problem seems to be solved.
