### ISSUE TITLE
VS Code hangs when using ParseTODOs (all files)

### ISSUE THREAD

**Issue by mlc-mlapis** [kantlove/vscode-todo-parser#19]
Hi,

I have a problem when using the command "ParseTODOs (all files)". VS Code hangs immediately. On individual documents it works as supposed.

**My config:**
```
"TodoParser": {
        "exclude": ["cpp", "c"],
        "folderExclude": ["node_modules", ".vscode", "typings"],
        "markers": ["@todo"]
}
```
**Environment:**
- Windows 8.1
- node 0.12.15
- VS Code 1.4.0
- todo-parser 1.7.2

**Comment by kantlove** [comment]
Could you update the extension to v1.8.0 and check again?

**Comment by mlc-mlapis** [comment]
I did and can confirm that the problem disappeared. Great. Thanks.

But there is a new side effect. When I run "ParseTODOs (all files)" all files are processed to find TODOs but in the same time other TS Code extensions are invoked - namely "Stylelint" and "Spelling and Grammar Checker" and they process those files also. It is a very frustrating efect.

**Comment by kantlove** [comment]
I have created a separate issue for this #23. That's a good point :+1:
