### ISSUE TITLE
show todo's of all files in current project

### ISSUE THREAD

**Issue by maxfriedmann** [kantlove/vscode-todo-parser#2]
It might be an unperformant operation, but could you show all todo's that are present in the current opened folder? I would really appreciate a side window where you can go through them since I got used to "todo bookmark" a lot of source files in other IDEs where that was supported.

**Comment by kantlove** [comment]
I really want to do that too. However, I'm busy with university thesis so cannot promise that feature will come out soon :sweat:

**Comment by maxfriedmann** [comment]
ok, no worries! I totally understand! Good luck with your thesis! ;-)

**Comment by kantlove** [comment]
Implemented in v1.2 #3 :+1:

**Comment by galvanu** [comment]
Hi, i'm using the extension version 1.3.2 but I still can't find a way to see all TODOs in the project, only for the current open file. Can you please give some more info how can I see all todos in the project?

**Comment by kantlove** [comment]
Can you send me the output of `>Parse TODOs (all files)`

**Comment by galvanu** [comment]
For file with no TODOs the output is empty, while in file that has any TODO I'll get a list of all TODOs.
(Event if I chose the all files option)

**Comment by kantlove** [comment]
You mean the list of all TODOs of opened files only or the list of all TODOs in the root folder (the folder that you opened with VSCODE)?

**Comment by galvanu** [comment]
Maybe I'm missing something.
Parse TODOs (all files)
should just parse them or display all of them?

I'm looking for a way to see all TODO's of the project under same view.
Wonder if this feature exists? Thanks!

**Comment by kantlove** [comment]
**Parse TODOs (all files)** will parse TODOs in all supported files in side of the root folder (the folder that you opened). The result will be display in the bottom panel.

You said you have a list of all TODOs so I still don't get the problem. 

Could you give me more information? Like what do your files look like? What is your expected result and what is the real result?

**Comment by galvanu** [comment]
I think everything works fine according to your description.
I'm looking for a way to see all my TODOs (for all project files) under the same windows.
Currently I can see TODO's for the active file and the counter at the bottom bar show the number of TODOs in the current active file

**Comment by kantlove** [comment]
No it should find TODOs in all files shown on the side bar not only active files (i.e. all project files). There is something wrong.

May I have a screenshot of your project directory tree?
