### ISSUE TITLE
Combination of TODO Parser with Vim extensions 100% CPU usage

### ISSUE THREAD

**Issue by andradei** [kantlove/vscode-todo-parser#21]
With TODO Parser and a Vim extension installed, opening a `.gitignore` file causes VSCode to spawn multiple _Code Helper_ processes that use more than 90% CPU

<img width="586" alt="screen shot 2016-08-25 at 22 29 15" src="https://cloud.githubusercontent.com/assets/2653546/17995801/e7d33ca2-6b21-11e6-8d35-f38241922403.png">

Uninstalling TODO Parser resolves the problem.

For reference: https://github.com/aioutecism/amVim-for-VSCode/issues/124

**Comment by kantlove** [comment]
Could you update the extension and try again?
It seems ok on my machine. I think the problem is resolved.

**Comment by andradei** [comment]
It is working now. Thanks.
