### ISSUE TITLE
Extension annoying

### ISSUE THREAD

**Issue by tigerxy** [kantlove/vscode-todo-parser#24]
Hey,

your extension is great, but very annoying for extension developers. Every time I am in debugging mode and switch between files, the extension [reject](/kantlove/vscode-todo-parser/blob/master/src/classes/FileReader.ts#L21) the error. Please fix it.

Best regards

**Comment by kantlove** [comment]
Sorry for that, I will silent that 'reject' 👍 
Please update the extension to v1.8.2
