### ISSUE TITLE
parse html (and html-like) files

### ISSUE THREAD

**Issue by beeplin** [kantlove/vscode-todo-parser#27]
best vscode todo tools! but currently not support html `<!-- TODO: .....  -->`

furthermore, when developping with vue, we always write js\coffee\… code directly in .the < script> part of a .vue file (can be treated as a html file), and write css directly in .vue file's < style> part.

so in a html or html-like file, it may have three or more types of todos to be parsed: html's < !-- ... -z>, js //, coffee #, css /\* ... */.

**Comment by beeplin** [comment]
Now I have a workaround: use `<!-- // TODO: xxx --> ` in vue's html part, and ` # // TODO: xxx` in vue's coffee part.

**Comment by kantlove** [comment]
Cool! :+1: 
The reason there is no html support yet is because there can be other types of languages embedded in it (e.g. JS). And sadly I don't have time to implement it :((

**Comment by facelesspanda** [comment]
Minor bummer (but still, should  be noted)
when writing `<!-- //TODO: task -->`, the todo output panel will list `task -->` as the task.

Completely negligible, but I just wanted that people coming here to find an answer for html comments wouldn't be surprised seeing that arrow when using that workaround.
Just being thorough.

**Comment by nooldey** [comment]
when I was using this format  in **html** files, it seems output good!
```
<!-- 
        //TODO: some task
 -->
```
then it output just `some task` without the arrow

hope it help
