### ISSUE TITLE
Link to files with spaces do not work

### ISSUE THREAD

**Issue by con-ssc** [kantlove/vscode-todo-parser#32]
I have space in filenames and paths and the parsed list cuts the link at the first space so clicking on the link ends up trying to open a file that does not exist at this point.

**Comment by zakaluka** [comment]
I installed this extension today on VS Code on windows 7 and saw this as an open issue.  I setup a simple test, and received the following output.  It shows that spaces (at least in the filename) were replaced with `%20`.

```
1.
From file:///c%3A/Users/SVShah/Projects/fsaoc2016/5/Test%20for%20todo.fsx#1
----------------------------------
TODO does this work?

==================================
Found 1 TODO.
```

Clicking the link took me to the correct file and line.  

Could this problem be OS (or version) specific?  Also, my filename has spaces in it, but not my path.  Not sure if that makes a difference or not.

**Comment by DavidBabel** [comment]
Got the same problem on MacOs Sierra

**Comment by kantlove** [comment]
I think this one is OS specific. Tried to reproduce it on Windows by using space in path. It's still ok:
The path is something like: `.../test/samples/spaced path/cpp.cpp`
```
2.
From file:///d%3A/MyDocument/Programming/js-projects/vscode-todo-parser/test/samples/spaced%20path/cpp.cpp#7
----------------------------------
Todo: cpp multiline
todo
```
