### ISSUE TITLE
Feature Request: Could you implement the exclude feature for markers setting?

### ISSUE THREAD

**Issue by momoko8443** [kantlove/vscode-todo-parser#33]
> **markers**
Contains the words that signal the start of TODOs. For example, "markers": ["NOTE:"] will enable matching NOTE: this is a new type of TODO.
Note that "TODO:", "Todo:", and "todo:" are added by default.

For example , I added  `{"markers": ["Refactoring:"] }` to my user settings.json, I hope todo-parser only lists "Refactoring:" items to me, excludes default "TODO:" , "Todo:" and "todo:" , because  existed **Todos** were marked by other people, I don't care them.

Maybe we can improve the settings file ,just like 
`{"markers": ["!TODO:","!Todo:","Refactoring:"] }`

Thanks

**Comment by kantlove** [comment]
I'll do a switch in setting to turn off the default markers. Hope that is ok with your use case :)

Please wait for the next version. Thanks for your suggestion 👍

**Comment by momoko8443** [comment]
Await for next release. :+1:
