### ISSUE TITLE
TODO after commenting a line of code does not work

### ISSUE THREAD

**Issue by andrewspy** [kantlove/vscode-todo-parser#36]
Not sure if this is a limitation, but the ability to retain a TODO after commenting a line of code with TODO is useful.

```javascript
// let i = 0; // TODO: Not recognised!
let i = 1; // TODO: Working fine
```

**Comment by kantlove** [comment]
Yes, it is indeed a limitation. Currently, the extension tries to find the keyword (e.g. "TODO") at the beginning of a line only.
