### ISSUE TITLE
No TODO list

### ISSUE THREAD

**Issue by Gruntfuggly** [kantlove/vscode-todo-parser#47]
It parses and finds my todo's, but they aren't displayed anywhere? From the screenshot, it looks like there is supposed to be a group in the explorer, but I don't see anything 8-(

**Comment by kantlove** [comment]
The TODOs are supposed to be in a separate panel. To show it you can: 

- Press the small button with the number of TODOs at the bottom bar.
- Press **F1** and run the command `> Parse TODOs (all files)`

**Comment by Gruntfuggly** [comment]
Where is the separate panel?  This is the result of clicking the small button...

![todo](https://cloud.githubusercontent.com/assets/376658/22863203/b55f2554-f133-11e6-9d73-4822d43cf508.png)

**Comment by kantlove** [comment]
The TODO is displayed in this panel 
![capture](https://cloud.githubusercontent.com/assets/8610576/23338192/01f8de80-fc3f-11e6-9533-a866dd5c994e.JPG)
