### ISSUE TITLE
Matlab language support

### ISSUE THREAD

**Issue by foxtrot9** [kantlove/vscode-todo-parser#48]
It would be great if extension supports independent parsing of todos rather than in comments.
Otherwise it would be awesome if extension supports MATLAB.

**Comment by kantlove** [comment]
Thanks for your suggestion. The idea behind todos in comments is because in my experience, it it a consistent way to add a todo without affecting the code.
But I'd like to listen to your suggestion on other places that we can put our todo too 👍

**Comment by kantlove** [comment]
Matlab support is added in v1.8.7
