### ISSUE TITLE
TODO markers should only be detected at comment start

### ISSUE THREAD

**Issue by pmcoz** [kantlove/vscode-todo-parser#52]
Currently, comments such as
`// Here, we look for strings containing TODO`
are picked up as TODO tasks. This is rarely a problem when using TODO, but can be more of a problem when using other markers. Would it be preferable to ensure that the marker is at the **_start_** of the comment text before considering it to be a task?

**Comment by kantlove** [comment]
Thanks for reporting this.
Which programming language is used? 
Could you provide me a sample of your code file that contains that comment?

**Comment by pmcoz** [comment]
Language is JS.

I can do better than provide a sample of my code: I can provide a sample of YOUR code! :)
[todo.zip](https://github.com/kantlove/vscode-todo-parser/files/852220/todo.zip)

This case is unusal enough to ignore, but the issue could be more of a problem if one used a marker such as FIX, and had a comment such as // This code is to fix a rounding problem

**Comment by kantlove** [comment]
Thanks, will include the fix in the next version 👍

**Comment by pmcoz** [comment]
Thanks!

Let me add that I wouldn't use VS Code if it wasn't for this extension of yours; it's just SO useful.
