### ISSUE TITLE
Integration with Problems panel

### ISSUE THREAD

**Issue by AlekSi** [kantlove/vscode-todo-parser#53]
I was surprised to see my FIXMEs and TODOs in separate Output panel, not in Problems panel.

**Comment by kantlove** [comment]
Well, the output panel code was before VSCode has Problem panel. 
However, I think it makes sense that TODOs are displayed in the Output panel since it is essentially an output and not a problem.

**Comment by AlekSi** [comment]
Items at Problems panel has levels so you can use ℹ️ Info for `TODO` and ⚠️ Warning for `FIXME`, for example. It would look better that plain text at Output panel.

**Comment by richarddavenport** [comment]
@AlekSi That's a fantastic idea! The output panel is a little unfriendly, moving to the problems panel would be much better.

**Comment by tehKaiN** [comment]
Yup, integration with Problems would be great, I guess it would improve readability.
Also, would be great to have all TODOs listed from entire project, not just active file.

**Comment by peacegiverman** [comment]
I just submitted a PR (#65) which fixes this issue. If you're in a hurry, feel free to get the extension from [my repo](https://github.com/peacegiverman/vscode-todo-parser/tree/problems-panel) (note the new settings options).

**Comment by peacegiverman** [comment]
Here's a screenshot.

![](http://i.imgur.com/9QofDgy.png)
