### ISSUE TITLE
Cached response

### ISSUE THREAD

**Issue by annalinneajohansson** [kantlove/vscode-todo-parser#58]
Love the extension but it seems to be stuck in returning a cached response for me. I'm getting the todo I first added, but after updating the file in question with several more (and also removing the first todo), I'm still getting that first todo returned (and none of the new ones).

**Comment by pmcoz** [comment]
Have you tried clicking on the TODO icon in the bottom status bar?

**Comment by annalinneajohansson** [comment]
Yes, I've used both that and the command list. Same response.

**Comment by annalinneajohansson** [comment]
I also tried with clearing the console output, restarting Visual Studio Code and un- and reinstallning the extension.

**Comment by kantlove** [comment]
Hi @annalinneajohansson,
Can you try switching to another file and switch back?

**Comment by annalinneajohansson** [comment]
No luck; now I'm instead getting _No TODOs found_. 

I've tried a couple of different markers to, but it doesn't detect any of them: @todo, @TODO, TODO and TODO:

I'm on Ubuntu 16.10, GNOME 3.20.4 in case that makes any difference @kantlove

**Comment by annalinneajohansson** [comment]
Found the issue: I'd added my TODO:s in docblocks as so:

`/**
* TODO
*/`

and it doesn't seem to detect them when I do so.

**Comment by kantlove** [comment]
Can I know what language you are using?

**Comment by annalinneajohansson** [comment]
The files I've tested are in PHP

**Comment by kantlove** [comment]
@annalinneajohansson thank you for reporting this 👍 

The extension cannot recognize multi-line comments starting with `/**` (2 asterisks)
But this is fixed in v1.8.10
