### ISSUE TITLE
Feature Request: HTML TODO comments please!

### ISSUE THREAD

**Issue by iandstanley** [kantlove/vscode-todo-parser#6]
would love this to be able to parse a TODO comment in HTML files

**Comment by rbenson** [comment]
Just seeing where this is on the radar. Is it more than adding HTML to  vscode-todo-parser/src/types/LanguageType.ts ?

**Comment by kantlove** [comment]
Check out the steps to add a new language in **src/docs/documentation.md**.
I did tried to add HTML but the performance in large files is really a problem.
