### ISSUE TITLE
showInProblems should disable output window

### ISSUE THREAD

**Issue by johannes-z** [kantlove/vscode-todo-parser#68]
If you use the `showInProblems` configuration, the plugin would still output `Found X TODOs.` in the output window, stealing focus from the Problems tab. Having to change tabs all the time is very annoying.

**Comment by kantlove** [comment]
Hi @johannes-z 
Thank you for reporting this bug. It is fixed in [v1.9.1](https://github.com/kantlove/vscode-todo-parser/releases/tag/1.9.1)
