### ISSUE TITLE
Every time I click the TODOs icon a new output panel is created.

### ISSUE THREAD

**Issue by robertohuertasm** [kantlove/vscode-todo-parser#7]
I'm using Windows 10 and insiders build.

![image](https://cloud.githubusercontent.com/assets/696981/16749256/356151b0-47c9-11e6-8e01-1aacfa257e52.png)

**Comment by buzouxun** [comment]
Same issue here. Windows 7. 
The TODO icon is the icon at bottom-left corner

**Comment by kantlove** [comment]
Thanks for your feed back, will fix this in a few days.

**Comment by kantlove** [comment]
Fixed in c7f142c. Please update the extension to v1.3.1
