### ISSUE TITLE
Unable to parse pre-existing TODOs in docuemnts

### ISSUE THREAD

**Issue by grapho** [kantlove/vscode-todo-parser#8]
I have a number of TODO lines in comment doc blocks in an existing code base.

todo-parser does not pick them up  It wil lonly register new TODOs as I type new ones in

Here is an example of one of my pre existing comments

```
/**
 * All the client based routes
 *
 * TODO: Possible Engine?
 *
 * @param   {String}
 * @param   {Function}
 * @private
 */
```

**Comment by kantlove** [comment]
This is in fact the way it worked. I've changed the parser strategy to solve your issue.
Please update to v1.3.2
